version: "3.7"
services:
    awpcode:
        container_name: awpcode
        build:
            dockerfile: ./Dockerfile
            context: .
        logging:
            driver: "json-file"
        ports:
            - "7070:1337"
