version: "3"
services:
    quiz:
        build: .
        ports:
            - "20003:3000"
        restart: always
        tty: true
        stdin_open: true
        environment:
            - FLAG=ping{FAKE}
