

# This file was *autogenerated* from the file encrypt.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1000 = Integer(1000); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_128 = Integer(128)
from sage.geometry.hyperbolic_space.hyperbolic_isometry import moebius_transform


CC = ComplexField(_sage_const_1000 )
M = random_matrix(CC, _sage_const_2 , _sage_const_2 )
f = lambda z: moebius_transform(M, z)

for _ in range(_sage_const_3 ):
  z = CC.random_element()
  print(f'{z}, {f(z)}')

kz = CC.random_element()
print(kz)
kw = f(kz)

mod = _sage_const_2 **_sage_const_128 
key = (kw.real() * mod).round() % mod
iv = (kw.imag() * mod).round() % mod

print(key, iv)

