# Generated by Gemini Pro

#!/usr/bin/env python3
from pwn import *
import re

# --- CONFIGURE THIS ---
HOST = "amt.rs"
PORT = 42529


# ----------------------

def get_values(r):
    """Gets n and one ciphertext from the server."""

    # Wait for the prompt for 'n' and 'e'
    # n, e = (20..., 3)
    r.recvuntil(b'n, e = (')
    n_str = r.recvuntil(b',', drop=True).decode()
    n = int(n_str)
    r.recvuntil(b')')  # Consume the rest

    # Send '0' for the scramble
    r.sendlineafter(b'scramble the flag: ', b'0')

    # Get the ciphertext
    # c = 123...
    r.recvuntil(b'c = ')
    c_str = r.recvline().decode().strip()
    c = int(c_str)

    return n, c


def main():
    try:
        # First connection
        log.info("Connecting to server for c1...")
        r1 = remote(HOST, PORT)
        n, c1 = get_values(r1)
        r1.close()
        log.success(f"Got n and c1:\nn = {n}\nc1 = {c1}")

        # Second connection
        log.info("Connecting to server for c2...")
        r2 = remote(HOST, PORT)
        # We discard 'n' from this one, just need c2
        _, c2 = get_values(r2)
        r2.close()
        log.success(f"Got c2:\nc2 = {c2}")

        print("\n" + "=" * 50)
        print("PASTE THESE VALUES INTO solve.sage:")
        print(f"n = {n}")
        print(f"c1 = {c1}")
        print(f"c2 = {c2}")
        print("=" * 50)

    except Exception as e:
        log.error(f"Failed to connect or parse: {e}")
        log.info(f"Make sure HOST '{HOST}' and PORT '{PORT}' are correct.")


if __name__ == "__main__":
    main()
